name: Publish
on:
  push:
    tags:
    - 'v*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Publish
      run: cargo publish --no-verify
